"""Framework-independent logical graph relations.

This module owns graph semantics and the framework-independent debug/runtime
realizers needed by native GraphForge tensors. It contains no topology builder
from NumPy, Torch, or another array framework. Dynamic relations stay
procedural until compiler/runtime lowering selects a physical builder; an
explicit native ``resolve_csr()`` may realize a cached snapshot for execution
or inspection. Optional framework inputs are dispatched to ``graphforge.interop``.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product
import math
from types import SimpleNamespace
from typing import Literal, Mapping

from ..distributed import ByDestination, DeviceMesh, GraphPlacement
from ..runtime import Device
from ..tensor import DType, Tensor, int32, int64, tensor
from .storage import PagedCSRStore


_INDEX_DTYPES = (int32, int64)


@dataclass(frozen=True)
class GraphSchema:
    num_src: int
    num_dst: int
    origin: str
    lifecycle: str
    realization: str
    index_dtype: DType
    sorted_by_dst: bool

    def specialization_key(self) -> tuple[object, ...]:
        return (
            self.num_src,
            self.num_dst,
            self.origin,
            self.lifecycle,
            self.realization,
            self.index_dtype.name,
            self.sorted_by_dst,
        )


@dataclass(frozen=True)
class DenseCellDirectory:
    """Compiler-selected physical directory for generated radius traversal."""

    cell_ptr: Tensor
    particle_order: Tensor
    cell_coordinates: Tensor
    extents: Tensor
    strides: Tensor
    neighbor_offsets: Tensor
    lattice: Tensor
    inverse_lattice: Tensor
    cutoff: float
    periodic: bool = False


class Graph:
    """Immutable logical relation over GraphForge tensors.

    Static CSR owns two index tensors. Dense and radius relations are implicit
    and must be tiled/generated by compiler passes; the semantic object never
    silently materializes an O(N^2) adjacency.
    """

    _graphforge_graph = True

    def __init__(
        self,
        schema: GraphSchema,
        *,
        row_ptr: Tensor | None = None,
        col_idx: Tensor | None = None,
        positions: Tensor | None = None,
        source_positions: Tensor | None = None,
        cutoff: float | Tensor | None = None,
        k: int | None = None,
        periodic: Tensor | None = None,
        exclude_self: bool = True,
        builder_fields: Mapping[str, Tensor] | None = None,
        metric: object | None = None,
        select: object | None = None,
        dense_boundary: str = "full",
        device: Device | str | None = None,
        placement: GraphPlacement | None = None,
        paged_store: PagedCSRStore | None = None,
    ) -> None:
        self._schema = schema
        self._row_ptr = row_ptr
        self._col_idx = col_idx
        self._positions = positions
        # None is the homogeneous/self-relation sentinel.  A distinct tensor
        # makes the same Graph type represent bipartite query/candidate search.
        self._source_positions = source_positions
        self._cutoff = cutoff
        self._k = k
        self._periodic = periodic
        self._exclude_self = exclude_self
        self._builder_fields = dict(builder_fields or {})
        self._metric = metric
        self._select = select
        if dense_boundary not in {"full", "lower_inclusive"}:
            raise ValueError("dense_boundary must be 'full' or 'lower_inclusive'")
        self._dense_boundary = dense_boundary
        self._device = Device.parse(device or "cpu")
        self._placement = placement
        self._paged_store = paged_store
        self._degree_bounds_cache: tuple[int, int] | None = None
        self._degree_sum_cache: int | None = None
        self._source_index_span_ratio_cache: float | None = None
        self._torch_view_cache = None
        self._native_csr_snapshot: tuple[object, ...] | None = None
        self._native_csr_cache: tuple[Tensor, Tensor] | None = None
        self._native_build_info: dict[str, object] | None = None

    @staticmethod
    def _is_native(value: object) -> bool:
        return isinstance(value, Tensor)

    @staticmethod
    def _validate_index_tensor(name: str, value: Tensor) -> None:
        if not isinstance(value, Tensor):
            raise TypeError(f"{name} must be a graphforge.Tensor")
        if value.ndim != 1:
            raise ValueError(f"{name} must be one-dimensional")
        if value.dtype not in _INDEX_DTYPES:
            raise TypeError(f"{name} must have gf.int32 or gf.int64 dtype")

    @classmethod
    def from_csr(
        cls,
        row_ptr,
        col_idx,
        *,
        num_src: int | None = None,
        sorted_by_dst: bool = True,
        validate: Literal["basic", "full"] = "basic",
    ):
        if not cls._is_native(row_ptr) or not cls._is_native(col_idx):
            from ..tensor import from_torch

            return cls.from_csr(
                from_torch(row_ptr),
                from_torch(col_idx),
                num_src=num_src,
                sorted_by_dst=sorted_by_dst,
                validate=validate,
            )
        cls._validate_index_tensor("row_ptr", row_ptr)
        cls._validate_index_tensor("col_idx", col_idx)
        if row_ptr.device != col_idx.device:
            raise ValueError("row_ptr and col_idx must be on the same device")
        if row_ptr.numel == 0:
            raise ValueError("row_ptr must contain at least the initial zero")
        num_dst = row_ptr.numel - 1
        if num_src is None:
            values = col_idx.tolist()
            num_src = max(values) + 1 if values else num_dst
        if num_src < 0:
            raise ValueError("num_src must be non-negative")
        if validate not in {"basic", "full"}:
            raise ValueError("validate must be 'basic' or 'full'")
        if validate == "full":
            rows = row_ptr.tolist()
            columns = col_idx.tolist()
            if rows[0] != 0 or rows[-1] != len(columns):
                raise ValueError("invalid CSR row pointer endpoints")
            if any(right < left for left, right in zip(rows, rows[1:])):
                raise ValueError("row_ptr must be monotonic")
            if any(column < 0 or column >= num_src for column in columns):
                raise ValueError("col_idx contains an out-of-range source index")
        schema = GraphSchema(
            num_src=num_src,
            num_dst=num_dst,
            origin="explicit",
            lifecycle="static",
            realization="materialized_csr",
            index_dtype=col_idx.dtype,
            sorted_by_dst=sorted_by_dst,
        )
        return cls(
            schema,
            row_ptr=row_ptr,
            col_idx=col_idx,
            device=row_ptr.device,
        )

    @classmethod
    def from_coo(
        cls,
        src,
        dst,
        *,
        num_src: int | None = None,
        num_dst: int | None = None,
    ):
        if not cls._is_native(src) or not cls._is_native(dst):
            from ..interop.torch.graph import Graph as TorchGraph
            from ..tensor import from_torch

            adapted = TorchGraph.from_coo(
                src, dst, num_src=num_src, num_dst=num_dst)
            row_ptr, col_idx = adapted.resolve_csr()
            return cls.from_csr(
                from_torch(row_ptr),
                from_torch(col_idx),
                num_src=adapted.schema.num_src,
            )
        cls._validate_index_tensor("src", src)
        cls._validate_index_tensor("dst", dst)
        if src.shape != dst.shape:
            raise ValueError("src and dst must have identical shapes")
        if src.device != dst.device:
            raise ValueError("src and dst must be on the same device")

        # COO import is an explicit topology-construction boundary.  The
        # framework-independent implementation synchronizes once, performs a
        # stable destination sort, and writes canonical CSR on the input
        # device.  Providers may replace this builder with a device sort later
        # without changing Graph semantics or the MessagePassing ABI.
        sources = src.tolist()
        destinations = dst.tolist()
        if num_src is None:
            num_src = max(sources) + 1 if sources else 0
        if num_dst is None:
            num_dst = max(destinations) + 1 if destinations else 0
        if not isinstance(num_src, int) or num_src < 0:
            raise ValueError("num_src must be a non-negative integer")
        if not isinstance(num_dst, int) or num_dst < 0:
            raise ValueError("num_dst must be a non-negative integer")
        if any(value < 0 or value >= num_src for value in sources):
            raise ValueError("src contains an out-of-range source index")
        if any(value < 0 or value >= num_dst for value in destinations):
            raise ValueError("dst contains an out-of-range destination index")

        order = sorted(range(len(sources)), key=destinations.__getitem__)
        columns = [sources[index] for index in order]
        counts = [0] * num_dst
        for value in destinations:
            counts[value] += 1
        rows = [0]
        for count in counts:
            rows.append(rows[-1] + count)
        return cls.from_csr(
            tensor(rows, dtype=dst.dtype, device=dst.device),
            tensor(columns, dtype=src.dtype, device=src.device),
            num_src=num_src,
            sorted_by_dst=True,
            validate="full",
        )

    @classmethod
    def open(cls, path, *, device: Device | str = "cpu") -> "Graph":
        """Open a persistent graph without eagerly loading its CSR arrays."""
        store = PagedCSRStore(path)
        schema = GraphSchema(
            num_src=store.num_src,
            num_dst=store.num_dst,
            origin="persistent",
            lifecycle="static",
            realization="paged_csr",
            index_dtype=store.index_dtype,
            sorted_by_dst=store.sorted_by_dst,
        )
        return cls(schema, device=device, paged_store=store)

    @classmethod
    def radius(
        cls,
        positions,
        cutoff,
        *,
        exclude_self: bool = True,
        fields: Mapping[str, Tensor] | None = None,
        metric: object | None = None,
        select: object | None = None,
        periodic: Tensor | object | None = None,
    ):
        if not cls._is_native(positions):
            from ..tensor import from_torch

            native_fields = {
                name: from_torch(value) for name, value in (fields or {}).items()
            }
            native_cutoff = (
                from_torch(cutoff)
                if type(cutoff).__module__.split(".")[0] == "torch"
                else cutoff
            )
            native_periodic = (
                from_torch(periodic)
                if periodic is not None
                and type(periodic).__module__.split(".")[0] == "torch"
                else periodic
            )
            return cls.radius(
                from_torch(positions),
                native_cutoff,
                exclude_self=exclude_self,
                fields=native_fields,
                metric=metric,
                select=select,
                periodic=native_periodic,
            )
        if positions.ndim != 2 or positions.dtype.kind != "float":
            raise TypeError("positions must be a rank-two floating gf.Tensor")
        if metric is not None and not callable(metric):
            raise TypeError("metric must be callable")
        if select is not None and not callable(select):
            raise TypeError("select must be callable")
        count = positions.shape[0]
        dimensions = positions.shape[1]
        if periodic is not None:
            if not isinstance(periodic, Tensor):
                raise TypeError("periodic must be a graphforge.Tensor")
            if periodic.shape not in {(dimensions,), (dimensions, dimensions)}:
                raise ValueError(
                    "periodic must contain box lengths [D] or lattice vectors [D,D]"
                )
            if periodic.dtype is not positions.dtype:
                raise TypeError("periodic and positions must have the same dtype")
            if periodic.device != positions.device:
                raise ValueError("periodic and positions must share a device")
        builder_fields = dict(fields or {})
        if "position" in builder_fields:
            raise ValueError("fields cannot redefine the reserved 'position' field")
        for name, value in builder_fields.items():
            if not isinstance(value, Tensor):
                raise TypeError(f"fields[{name!r}] must be a graphforge.Tensor")
            if not value.shape or value.shape[0] != count:
                raise ValueError(f"fields[{name!r}] leading dimension must be {count}")
            if value.device != positions.device:
                raise ValueError(f"fields[{name!r}] must share the positions device")
        schema = GraphSchema(
            num_src=count,
            num_dst=count,
            origin="geometric_radius",
            lifecycle="dynamic",
            realization="procedural_radius",
            index_dtype=int64,
            sorted_by_dst=True,
        )
        return cls(
            schema,
            positions=positions,
            cutoff=cutoff,
            periodic=periodic,
            exclude_self=exclude_self,
            builder_fields=builder_fields,
            metric=metric,
            select=select,
            device=positions.device,
        )

    @classmethod
    def knn(
        cls,
        positions,
        k: int,
        *,
        candidates=None,
        exclude_self: bool | None = None,
    ):
        """Create an exact procedural query-to-candidate kNN relation.

        ``positions`` are destination/query coordinates. Omitting
        ``candidates`` creates self-kNN and excludes each query from itself by
        default. Supplying candidates creates a bipartite relation whose
        candidates are source entities and whose queries are destinations.
        """
        if not cls._is_native(positions) or (
            candidates is not None and not cls._is_native(candidates)
        ):
            from ..tensor import from_torch

            return cls.knn(
                from_torch(positions), k,
                candidates=(
                    None if candidates is None else from_torch(candidates)
                ),
                exclude_self=exclude_self,
            )
        if positions.ndim != 2 or positions.dtype.kind != "float":
            raise TypeError("positions must be a rank-two floating gf.Tensor")
        self_search = candidates is None
        source_positions = positions if self_search else candidates
        assert isinstance(source_positions, Tensor)
        if source_positions.ndim != 2 or source_positions.dtype.kind != "float":
            raise TypeError("candidates must be a rank-two floating gf.Tensor")
        if source_positions.shape[1] != positions.shape[1]:
            raise ValueError("positions and candidates must share feature width")
        if source_positions.dtype is not positions.dtype:
            raise TypeError("positions and candidates must share dtype")
        if source_positions.device != positions.device:
            raise ValueError("positions and candidates must share device")
        if exclude_self is None:
            exclude_self = self_search
        if not isinstance(exclude_self, bool):
            raise TypeError("exclude_self must be bool or None")
        if exclude_self and not self_search:
            raise ValueError(
                "exclude_self is only defined for self-kNN; omit candidates"
            )
        query_count = positions.shape[0]
        source_count = source_positions.shape[0]
        maximum = source_count - 1 if exclude_self else source_count
        if not isinstance(k, int) or k <= 0 or k > maximum:
            raise ValueError(
                f"k must be in [1, {maximum}] for {source_count} candidates"
            )
        schema = GraphSchema(
            num_src=source_count,
            num_dst=query_count,
            origin="geometric_knn",
            lifecycle="dynamic",
            realization="procedural_knn",
            index_dtype=int64,
            sorted_by_dst=True,
        )
        return cls(
            schema,
            positions=positions,
            source_positions=None if self_search else source_positions,
            k=k,
            exclude_self=exclude_self,
            device=positions.device,
        )

    @classmethod
    def dense(
        cls,
        num_src: int,
        num_dst: int | None = None,
        *,
        device: Device | str | object | None = None,
        index_dtype: DType = int64,
    ):
        # A torch.device is an explicit compatibility request. Strings and
        # GraphForge Devices remain native and do not import Torch.
        if device is not None and type(device).__module__.split(".")[0] == "torch":
            device = str(device)
        if num_dst is None:
            num_dst = num_src
        if not isinstance(num_src, int) or num_src < 0:
            raise ValueError("num_src must be non-negative")
        if not isinstance(num_dst, int) or num_dst < 0:
            raise ValueError("num_dst must be non-negative")
        if index_dtype not in _INDEX_DTYPES:
            raise TypeError("index_dtype must be gf.int32 or gf.int64")
        schema = GraphSchema(
            num_src=num_src,
            num_dst=num_dst,
            origin="cartesian",
            lifecycle="static",
            realization="implicit_dense",
            index_dtype=index_dtype,
            sorted_by_dst=True,
        )
        return cls(schema, device=device)

    @classmethod
    def triangular(
        cls,
        num_entities: int,
        *,
        device: Device | str | object | None = None,
        index_dtype: DType = int64,
    ):
        """Create an implicit lower-triangular relation.

        Destination ``i`` is related to sources ``0..i``. This is a graph
        topology contract, not an attention operator; any MessagePassing UDF
        and reducer may consume it without materializing adjacency.
        """
        graph = cls.dense(
            num_entities, num_entities, device=device, index_dtype=index_dtype)
        graph._schema = GraphSchema(
            num_src=num_entities,
            num_dst=num_entities,
            origin="lower_triangular",
            lifecycle="static",
            realization="implicit_dense",
            index_dtype=index_dtype,
            sorted_by_dst=True,
        )
        graph._dense_boundary = "lower_inclusive"
        return graph

    @property
    def schema(self) -> GraphSchema:
        return self._schema

    @property
    def placement(self) -> GraphPlacement | None:
        return self._placement

    @property
    def is_distributed(self) -> bool:
        return self._placement is not None

    @property
    def device(self) -> Device:
        if self._col_idx is not None:
            return self._col_idx.device
        if self._positions is not None:
            return self._positions.device
        return self._device

    @property
    def num_edges(self) -> int | None:
        if self._schema.realization == "implicit_dense":
            if self._dense_boundary == "lower_inclusive":
                count = self._schema.num_dst
                return count * (count + 1) // 2
            return self._schema.num_src * self._schema.num_dst
        if self._paged_store is not None:
            return self._paged_store.num_edges
        return None if self._col_idx is None else self._col_idx.numel

    def resolve_csr(self) -> tuple[Tensor, Tensor]:
        if self._row_ptr is not None and self._col_idx is not None:
            return self._row_ptr, self._col_idx
        if self._paged_store is not None:
            # Explicit debugging/materialization request. Normal sharded
            # execution uses paged_rows() and never enters this branch.
            return self._paged_store.materialize(device=self.device)
        if self._schema.realization == "procedural_radius":
            if getattr(
                getattr(self._positions, "_buffer", None),
                "_graphforge_torch_buffer", False,
            ):
                from ..interop.torch.graph import from_native

                return from_native(self).resolve_csr()
            return self._resolve_native_radius_csr()
        # ``resolve_csr`` is an explicit request to materialize.  Keep it out
        # of normal compiler consumption, but allow the optional Torch oracle
        # to provide a correctness/debug realization when installed.
        try:
            from ..interop.torch.graph import from_native
        except ImportError as error:
            raise RuntimeError(
                "implicit/generated Graph requires a tiled compiler consumer; "
                "the optional Torch oracle is unavailable for explicit CSR debug"
            ) from error
        return from_native(self).resolve_csr()

    def _dynamic_snapshot(self) -> tuple[object, ...]:
        def token(value):
            return None if value is None else (id(value), value.version)

        return (
            token(self._positions),
            token(self._source_positions),
            token(self._cutoff) if isinstance(self._cutoff, Tensor) else self._cutoff,
            token(self._periodic),
            tuple((name, token(value)) for name, value in sorted(
                self._builder_fields.items())),
        )

    @staticmethod
    def _inverse_matrix(matrix: list[list[float]]) -> list[list[float]]:
        size = len(matrix)
        augmented = [
            [float(value) for value in row]
            + [1.0 if row_index == column else 0.0 for column in range(size)]
            for row_index, row in enumerate(matrix)
        ]
        for column in range(size):
            pivot = max(range(column, size), key=lambda row: abs(
                augmented[row][column]))
            if abs(augmented[pivot][column]) <= 1e-15:
                raise ValueError("periodic lattice must be invertible")
            augmented[column], augmented[pivot] = augmented[pivot], augmented[column]
            scale = augmented[column][column]
            augmented[column] = [value / scale for value in augmented[column]]
            for row in range(size):
                if row == column:
                    continue
                scale = augmented[row][column]
                augmented[row] = [
                    left - scale * right
                    for left, right in zip(augmented[row], augmented[column])
                ]
        return [row[size:] for row in augmented]

    def _periodic_matrices(self) -> tuple[list[list[float]], list[list[float]]] | None:
        if self._periodic is None:
            return None
        raw = self._periodic.tolist()
        dimensions = self._positions.shape[1]  # type: ignore[union-attr]
        lattice = (
            [[float(raw[row]) if row == column else 0.0
              for column in range(dimensions)] for row in range(dimensions)]
            if self._periodic.ndim == 1
            else [[float(value) for value in row] for row in raw]
        )
        return lattice, self._inverse_matrix(lattice)

    @staticmethod
    def _minimum_image(
        delta: list[float],
        matrices: tuple[list[list[float]], list[list[float]]] | None,
    ) -> tuple[list[float], list[float]]:
        if matrices is None:
            return delta, [0.0] * len(delta)
        lattice, inverse = matrices
        dimensions = len(delta)
        fractional = [
            sum(delta[component] * inverse[component][axis]
                for component in range(dimensions))
            for axis in range(dimensions)
        ]
        wrapped = [value - round(value) for value in fractional]
        minimum = [
            sum(wrapped[component] * lattice[component][axis]
                for component in range(dimensions))
            for axis in range(dimensions)
        ]
        return minimum, [raw - value for raw, value in zip(delta, minimum)]

    def _resolve_native_radius_csr(self) -> tuple[Tensor, Tensor]:
        if self._positions is None:
            raise RuntimeError("procedural radius graph has no positions")
        if (self._metric is not None or self._select is not None) and \
                self.device.type.name != "CPU":
            raise NotImplementedError(
                "native custom radius builder UDFs currently require CPU; "
                "the optional CUDA adapter or a provider lowering is required")
        snapshot = self._dynamic_snapshot()
        if snapshot == self._native_csr_snapshot and self._native_csr_cache is not None:
            return self._native_csr_cache
        cutoff = self._cutoff.tolist() if isinstance(self._cutoff, Tensor) \
            else self._cutoff
        if isinstance(cutoff, list) or cutoff is None:
            raise ValueError("radius cutoff must be a scalar")
        cutoff = float(cutoff)
        if not math.isfinite(cutoff) or cutoff < 0.0:
            raise ValueError("radius cutoff must be finite and non-negative")
        positions = self._positions.tolist()
        matrices = self._periodic_matrices()
        rows = [0]
        columns: list[int] = []
        cutoff_squared = cutoff * cutoff
        candidate_pairs = 0
        builder_name = "native_pair_scan"
        if self._metric is None and self._select is None:
            # A native debug/materialization request should not silently become
            # O(N^2) for the common non-periodic Euclidean case. Build a
            # uniform cell directory and visit only adjacent cells. Provider
            # code can use the same logical relation without materializing CSR.
            use_cell_list = matrices is None and cutoff > 0.0
            cells: dict[tuple[int, ...], list[int]] = {}
            if use_cell_list:
                for source, src_position in enumerate(positions):
                    coordinate = tuple(
                        math.floor(float(value) / cutoff)
                        for value in src_position
                    )
                    cells.setdefault(coordinate, []).append(source)
                offsets = tuple(product((-1, 0, 1), repeat=len(positions[0]))) \
                    if positions else ()
                builder_name = "uniform_cell_list"
            for destination, dst_position in enumerate(positions):
                if use_cell_list:
                    home = tuple(
                        math.floor(float(value) / cutoff)
                        for value in dst_position
                    )
                    sources = sorted(
                        source
                        for offset in offsets
                        for source in cells.get(tuple(
                            cell + shift for cell, shift in zip(home, offset)
                        ), ())
                    )
                else:
                    sources = range(len(positions))
                for source in sources:
                    if self._exclude_self and source == destination:
                        continue
                    candidate_pairs += 1
                    src_position = positions[source]
                    delta = [
                        float(src_position[axis]) - float(dst_position[axis])
                        for axis in range(len(src_position))
                    ]
                    delta, _ = self._minimum_image(delta, matrices)
                    if sum(value * value for value in delta) <= cutoff_squared:
                        columns.append(source)
                rows.append(len(columns))
        else:
            destinations = [
                destination for destination in range(len(positions))
                for source in range(len(positions))
                if not self._exclude_self or source != destination
            ]
            sources = [
                source for destination in range(len(positions))
                for source in range(len(positions))
                if not self._exclude_self or source != destination
            ]
            candidate_pairs = len(sources)
            builder_name = "native_pair_scan_udf"
            source_index = tensor(sources, dtype=int64, device=self.device)
            destination_index = tensor(
                destinations, dtype=int64, device=self.device)
            src_view, dst_view, edge_view = self._builder_pair_views(
                source_index, destination_index, cutoff)
            distance = (
                edge_view.distance if self._metric is None
                else self._metric(src_view, dst_view, edge_view)
            )
            if not isinstance(distance, Tensor) or distance.shape != (len(sources),):
                raise TypeError(
                    f"metric must return gf.Tensor[{len(sources)}]")
            distances = distance._evaluate_flat()
            selected = [value <= cutoff for value in distances]
            if self._select is not None:
                selection = self._select(
                    src_view, dst_view,
                    SimpleNamespace(
                        displacement=edge_view.displacement,
                        distance=distance,
                        cutoff=edge_view.cutoff,
                    ),
                )
                if not isinstance(selection, Tensor) or \
                        selection.dtype.name != "bool" or \
                        selection.shape != (len(sources),):
                    raise TypeError(
                        f"select must return gf.bool Tensor[{len(sources)}]")
                selected = [
                    keep and bool(choice)
                    for keep, choice in zip(selected, selection._evaluate_flat())
                ]
            cursor = 0
            for destination in range(len(positions)):
                for source in range(len(positions)):
                    if self._exclude_self and source == destination:
                        continue
                    if selected[cursor]:
                        columns.append(source)
                    cursor += 1
                rows.append(len(columns))
        result = (
            tensor(rows, dtype=int64, device=self.device),
            tensor(columns, dtype=int64, device=self.device),
        )
        self._native_csr_snapshot = snapshot
        self._native_csr_cache = result
        self._native_build_info = {
            "builder": builder_name,
            "candidate_pairs": candidate_pairs,
            "selected_pairs": len(columns),
            "reused_snapshot": False,
        }
        return result

    def _builder_pair_views(
        self, source_index: Tensor, destination_index: Tensor, cutoff: float
    ) -> tuple[SimpleNamespace, SimpleNamespace, SimpleNamespace]:
        if self._positions is None:
            raise RuntimeError("radius builder has no positions")
        source_position = self._positions.gather(source_index)
        destination_position = self._positions.gather(destination_index)
        displacement = source_position - destination_position
        matrices = self._periodic_matrices()
        if matrices is not None and source_index.numel:
            positions = self._positions.tolist()
            shifts = []
            for source, destination in zip(
                source_index.tolist(), destination_index.tolist()
            ):
                raw = [
                    float(positions[source][axis])
                    - float(positions[destination][axis])
                    for axis in range(self._positions.shape[1])
                ]
                _, shift = self._minimum_image(raw, matrices)
                shifts.append(shift)
            displacement = displacement - tensor(
                shifts, dtype=self._positions.dtype, device=self.device)
        distance = (displacement * displacement).sum(axis=1).sqrt()
        source_fields = {
            name: value.gather(source_index)
            for name, value in self._builder_fields.items()
        }
        destination_fields = {
            name: value.gather(destination_index)
            for name, value in self._builder_fields.items()
        }
        pair_count = source_index.numel
        cutoff_tensor = tensor(
            cutoff, dtype=self._positions.dtype, device=self.device
        ).broadcast_to((pair_count,))
        return (
            SimpleNamespace(position=source_position, **source_fields),
            SimpleNamespace(position=destination_position, **destination_fields),
            SimpleNamespace(
                displacement=displacement,
                distance=distance,
                cutoff=cutoff_tensor,
            ),
        )

    def implicit_edge_fields(
        self, row_ptr: Tensor, col_idx: Tensor
    ) -> dict[str, Tensor]:
        """Build differentiable geometry for one selected relation snapshot."""
        if type(row_ptr).__module__.split(".")[0] == "torch":
            from ..interop.torch.graph import from_native

            return from_native(self).implicit_edge_fields(row_ptr, col_idx)
        if self._schema.realization not in {
            "procedural_radius", "procedural_knn"
        } or self._positions is None:
            return {}
        if self._schema.realization == "procedural_knn":
            source_positions = (
                self._positions
                if self._source_positions is None
                else self._source_positions
            )
            destination = self.destination_index(row_ptr)
            displacement = (
                source_positions.gather(col_idx)
                - self._positions.gather(destination)
            )
            return {
                "displacement": displacement,
                "distance": (displacement * displacement).sum(axis=1).sqrt(),
            }
        rows = [int(value) for value in row_ptr.tolist()]
        destination = tensor(
            [row for row, (begin, end) in enumerate(zip(rows, rows[1:]))
             for _ in range(end - begin)],
            dtype=col_idx.dtype, device=col_idx.device,
        )
        src_view, dst_view, edge_view = self._builder_pair_views(
            col_idx, destination,
            float(self._cutoff.tolist()) if isinstance(self._cutoff, Tensor)
            else float(self._cutoff),
        )
        distance = (
            edge_view.distance if self._metric is None
            else self._metric(src_view, dst_view, edge_view)
        )
        if not isinstance(distance, Tensor) or distance.shape != (col_idx.numel,):
            raise TypeError(f"metric must return gf.Tensor[{col_idx.numel}]")
        return {"displacement": edge_view.displacement, "distance": distance}

    def degree_bounds(self) -> tuple[int, int]:
        if self._degree_bounds_cache is not None:
            return self._degree_bounds_cache
        if self._schema.realization == "implicit_dense":
            bounds = (
                (1, self._schema.num_src)
                if self._dense_boundary == "lower_inclusive"
                and self._schema.num_dst > 0
                else (self._schema.num_src, self._schema.num_src)
            )
            self._degree_bounds_cache = bounds
            return bounds
        if self._paged_store is not None:
            minimum = None
            maximum = None
            for _begin, _end, rows, _columns in self._paged_store.iter_pages(
                rows_per_page=65536
            ):
                for left, right in zip(rows, rows[1:]):
                    degree = right - left
                    minimum = degree if minimum is None else min(minimum, degree)
                    maximum = degree if maximum is None else max(maximum, degree)
            self._degree_bounds_cache = (
                (0, 0) if minimum is None else (minimum, maximum)
            )
            return self._degree_bounds_cache
        else:
            row_ptr, _ = self.resolve_csr()
            analyze = getattr(
                row_ptr._buffer, "adjacent_difference_bounds", None)
            if callable(analyze):
                self._degree_bounds_cache = analyze(
                    offset=row_ptr.offset,
                    stride=row_ptr.strides[0],
                    count=row_ptr.numel,
                )
                return self._degree_bounds_cache
            rows = row_ptr.tolist()
            degrees = [right - left for left, right in zip(rows, rows[1:])]
        self._degree_bounds_cache = (
            (min(degrees), max(degrees)) if degrees else (0, 0)
        )
        return self._degree_bounds_cache

    def degree_statistics(self) -> tuple[int, int, int]:
        """Return mergeable degree bounds and edge count for planning."""
        minimum, maximum = self.degree_bounds()
        if self._degree_sum_cache is None:
            self._degree_sum_cache = int(self.num_edges or 0)
        return minimum, maximum, self._degree_sum_cache

    def degree_histogram(self) -> tuple[int, ...]:
        minimum, maximum, _ = self.degree_statistics()
        del minimum
        if maximum > 4096:
            raise ValueError("exact degree histogram is limited to degree_max <= 4096")
        counts = [0] * (maximum + 1)
        if self._schema.realization == "implicit_dense":
            if self._dense_boundary == "lower_inclusive":
                for degree in range(1, maximum + 1):
                    counts[degree] = 1
            elif counts:
                counts[maximum] = self._schema.num_dst
        elif self._paged_store is not None:
            for _begin, _end, rows, _columns in self._paged_store.iter_pages(
                rows_per_page=65536
            ):
                for left, right in zip(rows, rows[1:]):
                    counts[right - left] += 1
        else:
            row_ptr, _ = self.resolve_csr()
            rows = row_ptr.tolist()
            for left, right in zip(rows, rows[1:]):
                counts[right - left] += 1
        return tuple(counts)

    def paged_rows(self, begin: int, end: int):
        """Compiler/runtime hook returning one bounded CSR destination tile."""
        if self._paged_store is None:
            raise TypeError("Graph is not backed by a paged CSR PhysicalInstance")
        return self._paged_store.read_rows(begin, end)

    def source_index_span_ratio(self, samples: int = 4096) -> float:
        """Return a deterministic physical source-index locality estimate."""
        if self._source_index_span_ratio_cache is not None:
            return self._source_index_span_ratio_cache
        if self._schema.realization == "implicit_dense":
            return 1.0 / 3.0
        row_ptr, col_idx = self.resolve_csr()
        analyze = getattr(
            col_idx._buffer, "csr_source_index_span_ratio", None)
        if callable(analyze):
            ratio = analyze(
                row_ptr=row_ptr,
                offset=col_idx.offset,
                stride=col_idx.strides[0],
                count=col_idx.numel,
                num_src=self._schema.num_src,
                num_dst=self._schema.num_dst,
                samples=samples,
            )
            self._source_index_span_ratio_cache = min(
                1.0, max(0.0, ratio))
            return self._source_index_span_ratio_cache
        rows = row_ptr.tolist()
        columns = col_idx.tolist()
        edges = len(columns)
        if edges == 0:
            ratio = 0.0
        else:
            count = min(samples, edges)
            slots = [
                0 if count == 1 else index * (edges - 1) // (count - 1)
                for index in range(count)
            ]
            row = 0
            total = 0
            for slot in slots:
                while row + 1 < len(rows) and slot >= rows[row + 1]:
                    row += 1
                total += abs(columns[slot] - row)
            ratio = total / count / max(
                1, self._schema.num_src, self._schema.num_dst)
        self._source_index_span_ratio_cache = min(1.0, max(0.0, ratio))
        return self._source_index_span_ratio_cache

    def euclidean_positions(self) -> Tensor | None:
        return (
            self._positions
            if self._schema.realization == "procedural_radius"
            and self._metric is None
            else None
        )

    def ranked_positions(self) -> tuple[Tensor, Tensor]:
        """Return query/candidate coordinates for a procedural ranked relation.

        This compiler-facing accessor preserves aliasing for self-kNN so the
        Domain verifier can prove that self exclusion refers to one entity
        domain. It never builds or caches adjacency.
        """
        if self._schema.realization != "procedural_knn" or self._positions is None:
            raise TypeError("ranked_positions requires a procedural kNN graph")
        return (
            self._positions,
            self._positions if self._source_positions is None
            else self._source_positions,
        )

    def generated_cell_directory(self):
        """Return an optional physical debug directory from the Torch oracle.

        Native compilation derives this in a graph-realization pass.  The
        method remains available for provider regression tests and interop.
        """
        try:
            from ..interop.torch.graph import from_native
        except ImportError:
            return None
        return from_native(self).generated_cell_directory()

    def halo(
        self,
        mesh: DeviceMesh,
        *,
        partition: ByDestination | None = None,
        depth: int | Literal["auto"] = "auto",
    ) -> "Graph":
        placement = GraphPlacement(mesh, partition or ByDestination(), depth)
        clone = object.__new__(Graph)
        clone.__dict__ = self.__dict__.copy()
        clone._builder_fields = dict(self._builder_fields)
        clone._placement = placement
        clone._torch_view_cache = None
        return clone

    def transpose(self) -> "Graph":
        """Return one materialized snapshot with endpoint roles swapped."""
        row_ptr, col_idx = self.resolve_csr()
        destination = self.destination_index(row_ptr)
        return type(self).from_coo(
            destination,
            col_idx,
            num_src=self._schema.num_dst,
            num_dst=self._schema.num_src,
        )

    def planning_key(self) -> tuple[object, ...]:
        """Stable logical planning key; physical adapters may refine it."""
        statistics = (
            self.degree_statistics()
            if self._row_ptr is not None or self._paged_store is not None
            or self._schema.realization == "implicit_dense"
            else "dynamic"
        )
        locality = (
            self.source_index_span_ratio()
            if self._row_ptr is not None else "paged-locality"
            if self._paged_store is not None else "dynamic-locality"
        )
        return (*self.specialization_key(), statistics, locality)

    def destination_index(self, row_ptr=None):
        if isinstance(row_ptr, Tensor):
            if getattr(
                getattr(row_ptr, "_buffer", None),
                "_graphforge_torch_buffer", False,
            ):
                from ..interop.torch.graph import from_native

                return from_native(self).destination_index(row_ptr.to_torch())
            rows = [int(value) for value in row_ptr.tolist()]
            return tensor(
                [row for row, (begin, end) in enumerate(zip(rows, rows[1:]))
                 for _ in range(end - begin)],
                dtype=row_ptr.dtype, device=row_ptr.device,
            )
        from ..interop.torch.graph import from_native

        return from_native(self).destination_index(row_ptr)

    def fixed_degree(self) -> int | None:
        minimum, maximum = self.degree_bounds()
        return minimum if minimum == maximum else None

    def sparse_csr(self, values=None):
        from ..interop.torch.graph import from_native

        return from_native(self).sparse_csr(values)

    @property
    def build_info(self) -> dict[str, object]:
        if (self._schema.realization == "procedural_radius" and
                isinstance(self._positions, Tensor) and
                not getattr(
                    getattr(self._positions, "_buffer", None),
                    "_graphforge_torch_buffer", False,
                )):
            reused = (
                self._native_csr_snapshot == self._dynamic_snapshot()
                and self._native_csr_cache is not None
            )
            self._resolve_native_radius_csr()
            assert self._native_build_info is not None
            return {**self._native_build_info, "reused_snapshot": reused}
        from ..interop.torch.graph import from_native

        return from_native(self).build_info

    def specialization_key(self) -> tuple[object, ...]:
        return (
            *self._schema.specialization_key(),
            str(self.device),
            None if self._placement is None else self._placement.specialization_key(),
            None if self._periodic is None else tuple(self._periodic.shape),
            self._k,
            self._source_positions is None,
            self._dense_boundary,
            None if self._paged_store is None else str(self._paged_store.path),
        )

    def explain(self) -> str:
        edges = "generated" if self.num_edges is None else f"{self.num_edges:,}"
        storage = (
            "" if self._paged_store is None
            else f", backing=nvme:{self._paged_store.path}"
        )
        udf = ""
        if self._schema.realization == "implicit_dense":
            udf = f", boundary={self._dense_boundary}"
        if self._positions is not None:
            udf = (
                f", metric={'custom' if self._metric is not None else 'euclidean'}"
                f", select={'custom' if self._select is not None else 'none'}"
                f", periodic={'none' if self._periodic is None else tuple(self._periodic.shape)}"
                f", broad_phase={'all-pairs-only' if self._metric is not None else 'euclidean-cell-list-eligible'}"
            )
            if self._k is not None:
                search = "self" if self._source_positions is None else "bipartite"
                udf = (
                    f", k={self._k}, search={search}, "
                    "builder=exact-provider-selected"
                )
        distributed = (
            "" if self._placement is None
            else f", halo={self._placement.halo_depth}"
        )
        return (
            f"Graph(origin={self._schema.origin}, lifecycle={self._schema.lifecycle}, "
            f"realization={self._schema.realization}, src={self._schema.num_src:,}, "
            f"dst={self._schema.num_dst:,}, edges={edges}, device={self.device}"
            f"{udf}{distributed}{storage})"
        )


__all__ = ["DenseCellDirectory", "Graph", "GraphSchema"]
