from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path


class FullMatrixTest(unittest.TestCase):
    def _write_fixture(self, root: Path) -> Path:
        manifest = {
            "showcase_panels": [{
                "title": "Edge UDF",
                "operation": "edge_udf", "case": "n128",
                "artifact": "results.json",
                "providers": ["tiga-compiled-tile", "warp-fused"],
                "baseline": "warp-fused",
            }],
            "operations": {
                "weighted_sum": {
                    "status": "measured-test",
                    "cases": ["regular_cuda_n1024_degree16_f16"],
                    "note": "test operation with registered gates",
                },
                "edge_udf": {
                    "status": "measured-test",
                    "cases": ["n128"],
                    "artifact": "results.json",
                    "note": "test operation without registered gates",
                },
            },
        }
        gate_payload = {
            "operation": "weighted_sum",
            "case": "regular_cuda_n1024_degree16_f16",
            "sota_gates": [{
                "topology": "regular", "locality": "random", "cache": "hot",
                "nodes": 1024, "edges": 16384, "features": 16,
                "index_dtype": "i32",
                "candidate": "tiga.prepared_auto",
                "baseline": "torch.sparse.mm",
                "candidate_ms": 0.0548, "baseline_ms": 0.2308,
                "speedup_vs_sota": 4.213,
                "speedup_ci_low": 4.153, "speedup_ci_high": 4.265,
                "threshold": 1.0, "passed": True, "reason": None,
            }],
            "results": [],
        }
        provider_payload = {
            "workload": "edge UDF",
            "results": [
                {"provider": "tiga-compiled-tile",
                 "milliseconds": 1.0199, "cache": "hot", "features": 8},
                {"provider": "warp-fused",
                 "milliseconds": 8.6702, "cache": "hot", "features": 8},
                {"provider": "torch-eager",
                 "milliseconds": 12.0685, "cache": "hot", "features": 8},
            ],
        }
        gate_dir = (
            root / "weighted_sum" / "regular_cuda_n1024_degree16_f16")
        gate_dir.mkdir(parents=True)
        (gate_dir / "roofline.json").write_text(json.dumps(gate_payload))
        provider_dir = root / "edge_udf" / "n128"
        provider_dir.mkdir(parents=True)
        (provider_dir / "results.json").write_text(
            json.dumps(provider_payload))
        manifest_path = root / "evidence_manifest.json"
        manifest_path.write_text(json.dumps(manifest))
        return manifest_path

    def test_includes_are_generated_from_gates_and_providers(self):
        from benchmarks.common import full_matrix

        with tempfile.TemporaryDirectory() as directory:
            workspace = Path(directory)
            manifest_path = self._write_fixture(workspace / "roofline")
            out_dir = workspace / "includes"
            en_path, zh_path = full_matrix.main(
                manifest_path=manifest_path,
                root=workspace / "roofline",
                out_dir=out_dir,
            )
            self.assertEqual(en_path, out_dir / "full-matrix.md")
            self.assertEqual(zh_path, out_dir / "full-matrix.zh.md")
            self.assertTrue(en_path.is_file())
            self.assertTrue(zh_path.is_file())

            en = en_path.read_text(encoding="utf-8")
            self.assertIn(
                "<!-- generated by python -m benchmarks.common.full_matrix;"
                " do not edit -->", en)
            self.assertIn("### weighted_sum { #matrix-weighted_sum }", en)
            self.assertIn("### edge_udf { #matrix-edge_udf }", en)
            # Gate row: candidate/baseline medians, speedup, 95% CI.
            self.assertIn(
                "<code>regular_cuda_n1024_degree16_f16</code>", en)
            self.assertIn("regular · random · hot · F16", en)
            self.assertIn("`tiga.prepared_auto` 0.055", en)
            self.assertIn("`torch.sparse.mm` 0.231", en)
            self.assertIn("4.21×", en)
            self.assertIn("[4.15, 4.26]", en)
            # Provider fallback: speedup against the panel-declared
            # warp-fused baseline (8.6702 / 1.0199 = 8.50).
            self.assertIn("`tiga-compiled-tile` | 1.020 "
                          "| `warp-fused` | 8.50×", en)

            zh = zh_path.read_text(encoding="utf-8")
            self.assertIn("### weighted_sum { #matrix-weighted_sum }", zh)
            self.assertIn("| 用例 | 分桶 |", zh)
            self.assertIn("加速比", zh)
            self.assertIn("通过", zh)
            self.assertIn("4.21×", zh)
            self.assertIn("8.50×", zh)


if __name__ == "__main__":
    unittest.main()
