"""CUDA physical index builder for generated Euclidean radius relations.

Fixed-size modular buckets avoid reading a bounding box back to the host.
Hash collisions add candidates, never edges: the compiler consumer still
checks Euclidean distance. This is not a periodic geometric boundary.
"""
from itertools import product
import weakref

import torch


def _point_keys_expression(positions, coordinates, keys, extents, strides, width):
    buckets = torch.floor(positions / width).to(torch.int64) & (extents - 1)
    coordinates.copy_(buckets)
    keys.copy_((buckets * strides).sum(-1))


# Physical Torch-adapter preprocessing, like its vendor sort below. Keep
# handwritten provider kernels out of the library; the query/reducer itself
# is generated by Tiga's Domain -> Iter -> Kernel -> TTIR pipeline.
_point_keys = torch.compile(_point_keys_expression, fullgraph=True, dynamic=True)


def build_hash_directory(positions, cutoff, pool):
    """Return independently owned indexes; recycle only private scratch buffers.

    Pools belong to a Graph, not to a process-global cache. Slots are separated
    by CUDA stream so reuse never races an earlier stream's index construction.
    """
    from .graph import DenseCellDirectory

    n, d = positions.shape
    # Around eight points per bucket; >=4 keeps all 3^D neighbor buckets unique.
    side = 4
    while side ** d < max(1, (n + 7) // 8):
        side *= 2
    cells = side ** d
    stream = torch.cuda.current_stream(positions.device).cuda_stream
    signature = (n, d, side, positions.device, stream)
    slot = next((slot for slot in pool if slot["signature"] == signature
                 and slot["owner"]() is None), None)
    if slot is None:
        def integer(shape):
            return torch.empty(shape, dtype=torch.int64, device=positions.device)
        slot = dict(signature=signature, owner=lambda: None, keys=integer(n), sorted_keys=integer(n),
                    order=integer(n), coordinates=integer((n, d)), ptr=integer(cells + 1),
                    extents=torch.full((d,), side, dtype=torch.int64, device=positions.device),
                    strides=torch.tensor([side ** axis for axis in range(d)], dtype=torch.int64, device=positions.device),
                    offsets=torch.tensor(list(product((-1, 0, 1), repeat=d)), dtype=torch.int64, device=positions.device),
                    boundaries=torch.arange(cells + 1, dtype=torch.int64, device=positions.device),
                    width=torch.tensor(cutoff, dtype=positions.dtype, device=positions.device),
                    cutoff=cutoff,
                    lattice=torch.eye(d, dtype=positions.dtype, device=positions.device))
        pool.append(slot)
    else:
        # Returned tensors may survive through detach()/storage aliases even
        # after the directory dies. Never overwrite their storage explicitly.
        slot["order"] = torch.empty(n, dtype=torch.int64, device=positions.device)
        slot["coordinates"] = torch.empty((n, d), dtype=torch.int64, device=positions.device)
        slot["ptr"] = torch.empty(cells + 1, dtype=torch.int64, device=positions.device)
    if slot["cutoff"] != cutoff:
        slot["width"].fill_(cutoff)
        slot["cutoff"] = cutoff
    with torch.no_grad():
        _point_keys(positions, slot["coordinates"], slot["keys"],
                    slot["extents"], slot["strides"], slot["width"])
        torch.sort(slot["keys"], stable=True, out=(slot["sorted_keys"], slot["order"]))
        torch.searchsorted(slot["sorted_keys"], slot["boundaries"], out=slot["ptr"])
    directory = DenseCellDirectory(
        cell_ptr=slot["ptr"], particle_order=slot["order"],
        cell_coordinates=slot["coordinates"], extents=slot["extents"],
        strides=slot["strides"], neighbor_offsets=slot["offsets"],
        lattice=slot["lattice"], inverse_lattice=slot["lattice"],
        cutoff=cutoff, hash_grid=True)
    slot["owner"] = weakref.ref(directory)
    return directory
