#!/usr/bin/env python3
"""Generate checked IR snapshots for the compiler walkthrough from one fixture."""

from __future__ import annotations

import argparse
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tests/mlir/distributed-plan.mlir"
STAGES = {
    "domain": (),
    "iter": ("-gf-lower-domain-to-iter",),
    "kernel": ("-gf-lower-domain-to-iter", "-gf-lower-iter-to-kernel",
               "-gf-select-kernel-schedule"),
    "task": ("-gf-lower-domain-to-iter", "-gf-lower-iter-to-kernel",
             "-gf-select-kernel-schedule", "-gf-plan-distributed-tasks"),
}


def render(gf_opt: Path) -> dict[str, str]:
    """Keep compiler output verbatim; only add provenance comments."""
    snapshots = {}
    for stage, flags in STAGES.items():
        result = subprocess.run(
            [str(gf_opt), str(SOURCE), *flags], check=True,
            capture_output=True, text=True, timeout=60,
        )
        snapshots[f"{stage}.mlir"] = (
            "// Generated by tools/render_ir_docs.py; do not edit.\n"
            "// Source: tests/mlir/distributed-plan.mlir\n"
            + result.stdout
        )
    return snapshots


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gf-opt", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path,
                        default=ROOT / "docs/includes/ir")
    parser.add_argument("--check", action="store_true",
                        help="fail on missing or stale snapshots without writing")
    args = parser.parse_args()
    snapshots = render(args.gf_opt.resolve())
    stale = []
    if not args.check:
        args.output_dir.mkdir(parents=True, exist_ok=True)
    for filename, content in snapshots.items():
        path = args.output_dir / filename
        if args.check:
            if not path.is_file() or path.read_text() != content:
                stale.append(filename)
        else:
            path.write_text(content)
    if stale:
        raise SystemExit("stale IR documentation: " + ", ".join(stale))
    print(f"{len(snapshots)} IR snapshots {'verified' if args.check else 'generated'}")


if __name__ == "__main__":
    main()
